---
title: ""
output:
  html_document:
    toc: TRUE
    toc_depth: 3
    toc_float: TRUE
    theme: spacelab
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{css, echo=FALSE}
p {
  font-size: 20px;
}
```


#### Welcome! This is personal repository where I store my slides decks for conference presentations, workshops, labs, and more.

# APA Style with RMarkdown

Check out this [minimum intro](./EDUC64322W/APA.html) for creating an .Rmd file with APA style 6th edition format.

# EDUC 641 2022 Fall Labs

#### [Lab 1 slides (week 1)](./EDUC64122F/lab1.html)

#### [Lab 2 slides (week 2)](./EDUC64122F/lab2.html)

 - [lab2 data](./EDUC64122F/ah_smoke.csv); 
 - [data description](./EDUC64122F/smoke.png)

#### [Lab 3 slides (week 3)](./EDUC64122F/lab3.html)

#### [Lab 4 slides (week 4)](./EDUC64122F/lab4.html) and [Lab 4 code](./EDUC64122F/code/lab4.R)

#### [Lab 5 slides (week 5)](./EDUC64122F/lab5.html)

#### [Lab 6 & 7 slides(Week 6 & 7)](./EDUC64122F/lab6.html)

#### [Lab 8 slides (week 8)](./EDUC64122F/lab8.html) and [Lab 8 code](./EDUC64122F/code/lab8.R)

#### [Lab 9 slides (week 9)](./EDUC64122F/lab9.html) and [Lab 9 code](./EDUC64122F/code/lab9.R)

#### No slides for week 10


# Conference presentations

## 2022

### SREE 2022

Date: 9/24/2022

Conference: SREE 2022

Location: Arlington, VA, USA

Session: 10A - Exploring the Role of Classroom Processes on Students

Paper title: Investigating Causal Impacts of Affective Teacher–Student Relationship on Student Cognitive and Non-Cognitive Outcomes

Authors: Congli (Claire) Zhang and Merly Klaas

#### [Check out our slides](./SREE2022/sree2022.html)

### AERA 2022

Date: 4/21/2022

Conference: SREE 2022

Location: San Diego, CA, USA

Session:  Division A - Administration / Section 2: School Organization and Effects / Explaining Student Outcomes: The Role of School Structures and Context

Paper title: Does Advisor-Advisee Relationship with Content Teacher Impact Student Learning? Causal Evidence from Chinese Middle Schools

Author: Congli (Claire) Zhang 

# About me

I am currently a doctoral candidate at the University of Oregon, majoring in Quantitative Research Methods in Education and specialized in Educational Data Science. I am professionally proficient in English and Chinese. My best programming language is R.  

As an educational researcher, I am interested in the causal impacts of school-, principal-, and teacher-level factors on student near- and long-term outcomes. My dissertation is focused on teacher effects, in which I analyze a nationally representative, longitudinal data from Chinese middle schools to examine whether and to what extent teacher human capital characteristics, advisor-advisee relationship, and classroom teacher-student relationship impact student academic performance. 

I am passionate about applying my knowledge and skills in quantitative methods and causal inference to education and social sciences research, with the goal to help policy makers, researchers, and educators understand what makes a good teacher, principal, and school, and how to improve the quality of public education. 

I will be graduating in June, 2023 and am currently on job market looking for academic positions in universities as well as applied analyst jobs in education research organizations. 

[Check out my website: http://congliclairezhang.com](http://congliclairezhang.com)

